modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Right Reserved"

[[mods]]
modId = "sponsor_core"
version = "${version}"
displayName = "Sponsor Core"
authors = "IAFEnvoy"
description = '''
'''
#logoFile = ""

[[dependencies.sponsor_core]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sponsor_core]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
