modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Right Reserved"

[[mods]]
modId = "sponsor_core"
version = "${version}"
displayName = "Sponsor Core"
authors = "IAFEnvoy"
description = '''
'''
#logoFile = ""

[[dependencies.sponsor_core]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sponsor_core]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[mixin]]
config = "sponsor_core.mixins.json"